"""Builds an Atlassian Document Format (ADF) Jira comment from an E2E
pipeline result. Reporting is a Jira comment only; Teams Adaptive Card
posting and ServiceNow ticket updates are not implemented.

Uses Jira's `panel` node (info/note/success/warning/error) for color-coded
severity -- the standard Atlassian formatting tool for this, rather than
inventing custom styling.
"""

import datetime

from app import classification_status, rca_status as rca_status_module

APP_NAME = "AIOps Triage Automation App"

STATUS_EMOJI = {"OK": "✅", "WARN": "⚠️", "ERROR": "❌"}

# Colored by rca_status (app.rca_status), not the internal matched_pattern:
# error (red) = a definitive cause; warning (yellow) = probable/needs a
# human/couldn't trace; note (gray) = inconclusive or already tracked
# elsewhere.
RCA_STATUS_PANEL_TYPE = {
    rca_status_module.IDENTIFIED: "error",
    rca_status_module.PROBABLE: "warning",
    rca_status_module.INCONCLUSIVE: "note",
    rca_status_module.CORRELATED: "note",
    rca_status_module.ISSUE_COULD_NOT_BE_TRACED: "warning",
    rca_status_module.NEED_MANUAL_INTERVENTION: "warning",
}


def _text(content: str, *, strong: bool = False) -> dict:
    node: dict = {"type": "text", "text": content}
    if strong:
        node["marks"] = [{"type": "strong"}]
    return node


def _paragraph(*inline) -> dict:
    return {"type": "paragraph", "content": list(inline)}


def _heading(level: int, content: str) -> dict:
    return {"type": "heading", "attrs": {"level": level}, "content": [_text(content)]}


def _bullet_list(items: list[str]) -> dict:
    return {
        "type": "bulletList",
        "content": [{"type": "listItem", "content": [_paragraph(_text(item))]} for item in items],
    }


def _panel(panel_type: str, *content_nodes) -> dict:
    return {"type": "panel", "attrs": {"panelType": panel_type}, "content": list(content_nodes)}


def build_rca_comment_adf(result: dict) -> dict:
    """result: the dict returned by app.e2e_pipeline.run_e2e_for_jira_key."""
    generated_at = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    classification = result["classification"]
    rca = result.get("rca")

    content: list[dict] = [
        _panel(
            "info",
            _paragraph(_text(f"\U0001f916 RCA generated by {APP_NAME}", strong=True)),
            _paragraph(_text(f"Generated: {generated_at}")),
        ),
        _heading(3, "Classification"),
        _paragraph(
            _text("Classification Status: ", strong=True),
            _text(classification_status.display_status(classification["status"])),
        ),
    ]

    if classification.get("source_system_id"):
        content.append(
            _paragraph(
                _text("Source System: ", strong=True),
                _text(str(classification["source_system_id"])),
                _text("    Category: ", strong=True),
                _text(str(classification["category"])),
            )
        )
    if classification.get("matched_rule_id"):
        content.append(_paragraph(_text("Matched Rule: ", strong=True), _text(str(classification["matched_rule_id"]))))

    if result.get("evidence"):
        content.append(_heading(3, "Evidence"))
        content.append(
            _bullet_list(
                [
                    f"{STATUS_EMOJI.get(e['status'], '')} {e['check']}: {e['details']}"
                    for e in result["evidence"]
                ]
            )
        )

    if rca is not None:
        panel_type = RCA_STATUS_PANEL_TYPE.get(rca["rca_status"], "note")
        content.append(
            _panel(
                panel_type,
                _paragraph(_text(f"RCA Status: {rca['rca_status']}", strong=True)),
                _paragraph(_text(rca["root_cause_summary"])),
            )
        )

        if rca.get("contributing_factors"):
            content.append(_heading(3, "Contributing Factors"))
            content.append(_bullet_list(rca["contributing_factors"]))

        if rca.get("recommended_actions"):
            content.append(_heading(3, "Recommended Actions"))
            content.append(_bullet_list(rca["recommended_actions"]))

    if result.get("evidence") and any("STUBBED" in e["details"] for e in result["evidence"]):
        content.append(
            _panel(
                "note",
                _paragraph(
                    _text(
                        "Evidence marked [STUBBED] is simulated for testing -- no real "
                        "monitoring/log/CI-CD integration is wired up yet. Do not treat as verified data."
                    )
                ),
            )
        )

    return {"type": "doc", "version": 1, "content": content}
